### ISSUE TITLE
Memory consuming

### ISSUE THREAD

**Issue by jeans11** [blueconic/browscap-java#59]
Hi guys!

I load / create a browscap parser (create once and reuse it) but the load increase of 2G my service memory.
Is all the `Rule` that are responsible of the huge memory gap?

Thanks

**Comment by paulrutter** [comment]
I haven't tested the exact memory usage lately, but this library is fast because it keeps all rules in memory in an efficiënt way. So that's indeed the instances of Rule.

**Comment by marcio-absmartly** [comment]
Sorry chime in after closed, but the primary issue is not the memory usage during operation, it's the memory usage and time spent during initialization building of these efficient structures. What we would need would be way to pre-compute this and ship it in the package, instead of building it every-time.

**Comment by paulrutter** [comment]
Ah right, i think that could be done be serializing the data structure to a file and deserializate on initialization.
Not sure if that would perform better in terms of memory, but worth a try.
PRs are welcome, i won't get to it.
